# SPDX-FileCopyrightText: Copyright 2022 EDF (Électricité de France S.A.)
# SPDX-License-Identifier: BSD-3-Clause
# See README for all details on copyright, authorship and license.
test:
  image: docker.io/python:3
  script:
    - pip install -r requirements.txt
    - python3 test.py
